### PR TITLE
Fix framepointer

### PR DESCRIPTION
**Pull request by Blei**
I'm not sure if this is 100% correct as it is now. At least all of the code that was reported to compile incorrectly works now.

### CODE REVIEW

**Comment by krasin** [comment]
If this CL makes any tests pass, we can mark the places where the fix is suboptimal and merge it.

**Comment by a1k0n** [comment]
Nice, I was trying to do the same thing yesterday but didn't get a chance to dig deep enough into it to figure out how.

**Comment by Blei** [comment]
@krasin I'm trying to rewrite the parts that required the ugly `BitsPerByte/8` hack. I'll see how far I get this evening.

**Comment by krasin** [comment]
Thank you, Philipp!

**Comment by Blei** [comment]
There are two FIXMEs left (in SelectionDAG.cpp 5690 & 5702). Not sure how to fix those. Otherwise the patch should be mostly clean now.

**Comment by a1k0n** [comment]
BTW, do you want me to pull request/merge this commit here: https://github.com/a1k0n/llvm-dcpu16/commit/2b8962ac4532ca236dcc3165d40ec53cb53d7d2b or is it obsolete?

I fixed a bunch more stuff in CodeGen with bytes, but I was sitting on it until some of the underlying issues, which you just did in this pull request, were fixed.  I may need to revisit my changes with these updates.

**Comment by Blei** [comment]
Re your patch: Looks good, and all the tests still work :) It would be great if you could make the failing tests you mentioned available.

The best course of action would probably be if you could rebase it on top of the current changes (if they get merged soon ;) ) and open a pull request.

**Comment by ghost** [comment]
Haven't had any time to test the changes (looks _very_ promising). Does this changeset also fix the stackpointer? (I assume it should, since it's basically the same code/problem)

**Comment by Blei** [comment]
It does indeed. I haven't found any failing code yet, so I'm hopeful that at least that part of llvm should work now :D

**Comment by a1k0n** [comment]
I still get a negative stack allocation size on the code in #163 with this patch.  Can't figure out why.

**Comment by Blei** [comment]
Hmm, I don't. What does your output look like? What compile options do you use?

**Comment by a1k0n** [comment]
Oh.  Umm, nevermind.  Works fine here.  I might have forgotten to compile it after switching branches.  Merge it!

**Comment by ghost** [comment]
Yep. LGTM. We should release an "SDK" now for easier use by new people. I will compile one with this patchset and will inlcude the binutils patched with dcpu16 support.

**Pull request merged**
