### PR TITLE
Switching branch targets and operands apparently is frowned upon.

### PR DESCRIPTION
**Pull request by Blei**
Might be related to #168.

### CODE REVIEW

**Comment by krasin** [comment]
Semi-blind LGTM. Feel free to merge when it's convenient.

**Comment by a1k0n** [comment]
Why is it frowned upon?  Or was there a particular bug?  I get pretty much the same output in #168 without the patch.

It could be useful especially in optimizing comparisons for instruction size, e.g. IFA 2,A is equiv but bigger and 1 cycle longer than IFU A,2 (because small immediates only work on the 'a' operand now), but that could be a peephole pattern.

**Comment by Blei** [comment]
@a1k0n, yes that's what I though (and what the intention of the original code was). The test that I included exposed a bug: it generates an `IFU 0x1, B` instead of `IFU B, 0x1`. I didn't dig deep enough to figure out why, but apparently this doesn't work... If you find out why and can reenable this optimization, I would be very grateful :)

**Comment by a1k0n** [comment]
Ah, ok.

Arguably if we change this code to generate separate if/set pc instructions in the DAG then we can just add some peephole patterns to correct these and keep the C++ side simple.  If my understanding of how this works is correct, that is.

**Comment by Blei** [comment]
Sounds correct, but I don't really have a clue either ;)

**Pull request merged**
