### PR TITLE
DCPU16: Rewrote the instruction tablegen to use multiclass

### PR DESCRIPTION
**Pull request by ghost**
This should be more easily maintainable, since we can now
add a new addressing mode to all arithmetic function by
simply adding it to the base multiclass.

@krasin : Could you please merge my pull request in the clang repo?
Blei and I don't have permission to do so.

### CODE REVIEW

**Comment by ghost** [comment]
Also removed all remaining "the Notch order" remainder, since we have fixed them all now.

**Comment by Blei** [comment]
LGTM, great work!

**Comment by krasin** [comment]
The change is very useful!

I will merge this by hand, by splitting the CL into a few (to convert one instruction per CL), as it's now hard to build a model of the change in my head.

Also, I would like to add more tests for this change. I will do that later today.

Thank you!

**Comment by krasin** [comment]
I'm in the process of splitting / merge. The preview is available here: e5676824d5820d3197d2b4fba62c4748961ce9c5

Unfortunately, I was interrupted earlier today (offline guests) and going to continue in 15 minutes.

**Comment by ghost** [comment]
Pull superseded by PR 123.

**Pull request closed without merging**
