### PR TITLE
Generate COFF sections instead of ELF sections for DCPU

### PR DESCRIPTION
**Pull request by a1k0n**

### CODE REVIEW

**Comment by a1k0n** [comment]
This is required for the current DCPU GNU binutils port.

**Comment by krasin** [comment]
Andy, thank you for working on this.

Could you please provide an evidence link?

**Comment by ghost** [comment]
As far as I understand, this change doesn't break any test cases and is necessary for the binutils port. LGTM
We should also think about re-activating the sections/pseudo opts we have deactivated. (#51 #52)

**Comment by a1k0n** [comment]
Without this patch, we generate in the assembly output, for example:

```
.section  .rodata,"a",@progbits
```

which is ELF-specific.  With this patch, it just generates ".data", sufficient for COFF.  The reason for this is just that GNU binutils only supports COFF for dcpu16, e.g.
https://github.com/frot/binutils-dcpu16/blob/master/bfd/coff-dcpu16.c

there is no elf-dcpu16 target support, so the assembler fails if there's any static data in the generated C code without this patch.

However, other bugs ( https://github.com/frot/binutils-dcpu16/issues/13 ) currently prevent it from generating correct code anyhow, so I'm recommending das ( https://github.com/jonpovey/das ) as a backend (with a patch to make it compatible) for now.

**Comment by krasin** [comment]
Thanks, Andy.

**Pull request merged**
