### PR TITLE
DCPU16: Renaming the register to DCPU16 specs

### PR DESCRIPTION
**Pull request by ghost**
Hopefully final attempt to rename all registers without failing big times. Please fell free to write advice.

Thanks for the advice from user 'asl'.

### CODE REVIEW

**Comment by ghost** [comment]
We should probably also revert commit ab2c06b5c464ecd8f67a13dd95d213529fbec017, since it deactivated the framepointer and right now, we could (should) use it.

**Comment by asl** [comment]
I commented on some lines in 9c7fd91 - found some typos. And yes, ab2c06b should be reverted as well, FP is required in that cases.

**Comment by ghost** [comment]
Updated the request. Will have to fix the PUSH instruction thought, since we use it now.

**Comment by krasin** [comment]
@arbaal I have no objections against this CL, but I fear to merge it w/o an LGTM from @asl :)

Anton, thank you for your valuable comments!

**Comment by asl** [comment]
LGTM :)

**Pull request merged**
