### PR TITLE
DCPU16: Restore constraints removed in #57.

### PR DESCRIPTION
**Pull request by krasin**
This fixes Inst16rr test.

@arbaal Nils, please, take a look. Feel free to merge this pull request, if it looks good to you.

krasin

### CODE REVIEW

**Comment by ghost** [comment]
Geez, couldn't sleep because of this, because I knew I might have introduced that bug. Looks fine for me, those constrains shouldn't have been deleted. I thought they would only be necessary when you had subregisters and wouldn't want to copy a value into the higher order reg.

**Comment by krasin** [comment]
Never mind, it happens.
I would suggest to spend the next day on adding more tests (fixing minor issues, like "The Notch order" is also fine)

**Comment by asl** [comment]
The constraints are definitely necessary, because they say that one of inputs is tied to output. Without register allocator will generate 3-address instruction (which looks like a = c op b), but then you print only a and b :)

**Comment by krasin** [comment]
Thanks for the explanation. That makes sense.

**Pull request merged**
