### PR TITLE
Update to LLVM upstream

### PR DESCRIPTION
**Pull request by krasin**

### CODE REVIEW

**Comment by krasin** [comment]
@Blei Can you please take a look? (also, for the Clang part)

**Comment by Blei** [comment]
Looks good, except for the failing X86 test. I would be ok with merging this, as the bug doesn't seem to be in our code. What do you guys think?

**Comment by krasin** [comment]
I am with you: I don't like this failure and will take another look tomorrow.

btw, I have found a way to rebuild Clang within 2.5 seconds on a whitespace / one-file change. This research has been done after requesting this pull, so I am now more comfortable with iterations.

In short, the secret is Gold + build as shared libraries + Ninja build instead of make.

**Comment by Blei** [comment]
Funny coincidence, I am just now checking out how good ninja works with LLVM ;) Thanks to #llvm I guess. I don't know about Gold though.

**Comment by ghost** [comment]
Would be nice to have a tutorial or howto to build out llvm tree with gold/ninja.

**Comment by krasin** [comment]
Wiki is already here: https://github.com/llvm-dcpu16/llvm-dcpu16/wiki/Llvm-with-ninja-build
I will slightly edit it to be more grammar-correct and shorter, but it's there with the benchmarks.

**Comment by krasin** [comment]
@Blei, I am not on #llvm but it might be something related, like Hacker News submission that has made me to try Ninja.

**Comment by Blei** [comment]
Found it. Some time back I changed register sizes to be in bits instead of bytes. Someone changed the X86 code without dividing by 8 (unsurprisingly, as the change is not upstream).

``` patch
diff --git a/lib/Target/X86/X86InstrInfo.cpp b/lib/Target/X86/X86InstrInfo.cpp
index 2310c4f..fb1e0a6 100644
--- a/lib/Target/X86/X86InstrInfo.cpp
+++ b/lib/Target/X86/X86InstrInfo.cpp
@@ -2595,7 +2595,7 @@ void X86InstrInfo::insertSelect(MachineBasicBlock &MBB,
    MachineRegisterInfo &MRI = MBB.getParent()->getRegInfo();
    assert(Cond.size() == 1 && "Invalid Cond array");
    unsigned Opc = getCMovFromCond((X86::CondCode)Cond[0].getImm(),
-                                  MRI.getRegClass(DstReg)->getSize());
+                                  MRI.getRegClass(DstReg)->getSize()/8);
    BuildMI(MBB, I, DL, get(Opc), DstReg).addReg(FalseReg).addReg(TrueReg);
 }

```

I can see this problem to reappear on each merge in the future. Actually, it's possible that there are already undetected bugs everywhere :S

**Comment by krasin** [comment]
My proposal:
1. Commit my two pull requests and merge your change as a separate pull request (I give an LGTM in advance for the diff above)
2. (optional) Since you're on #llvmdev, it might be useful to discuss non 8-bit bytes with them. Probably, we can spend some time to prepare a CL for the upstream. Not sure, though.

**Comment by Blei** [comment]
1. Sounds good.
2. Sounds much more tricky ;) Maybe I'll try it...

**Comment by krasin** [comment]
2 is not anyhow urgent and sounds really challenging, since LLVM team has thought on this topic more than once and it has never happened. But if you are already on the channel, asking a short question on the status of this problem would not probably hurt anyone.

**Comment by krasin** [comment]
thx for merging!

**Pull request merged**
