### PR TITLE
FIX for #Issue-61: Added basic MUL instruction

### PR DESCRIPTION
**Pull request by ghost**
Signed-off-by: Nils Hasenbanck nils@hasenbanck.de

### CODE REVIEW

**Comment by krasin** [comment]
Thank you!

You're really an LLVM expert!

**Comment by ghost** [comment]
Not really, just started hacking on LLVM for like 4 days? ...

**Comment by krasin** [comment]
the programmer expertise is measured not in the days on duty, but in the good CLs like the above

**Comment by krasin** [comment]
I have granted you a push access. Given that you're in significantly different time zone and I have enough confidence on you, it does not make sense to spend your time in waiting for my approval.

The only polite request is to try using pull requests and self-approve instead of git push.

Eventually (like in a week or so), I will convert my repository to the organization's repository and also will use git push for merging not-clean pull requests only.

**Comment by ghost** [comment]
Thanks for the trust, but the next some pull-requests will be rather big and will need peer review.

**Comment by krasin** [comment]
This is completely fine with me. :)

**Pull request merged**
