### PR TITLE
DCPU: 16bit addressing

### PR DESCRIPTION
**Pull request by ghost**
Okay, hell will start to freeze.

This is a quick for for enabling word based addressing
on the LLVM side. I added a new tag for the datalayout (W)
which defines if the new addressing mode should be used.
Right now it seems to work more or less. You HAVE to pull
the patch from clang to to make this work. Definitly not
a nice work of software engineering and it will break!

### CODE REVIEW

**Comment by krasin** [comment]
@arbaal Nils, would you mind if we put these changes into `word` branch? They are very risky, especially given the fact the DCPU16 specs are going to be updated 'soon'.

**Comment by krasin** [comment]
Forget branches. I have thought a little bit, we can go forward, even if that breaks us a bit. We're not stable yet, no need for this overhead.

**Comment by krasin** [comment]
The patch looks good to me, feel free to merge.

**Comment by ghost** [comment]
Okay, I will fix the minor problems, rebase and merge this patch.

**Pull request merged**
