### PR TITLE
DCPU16: Register fix

### PR DESCRIPTION
**Pull request by ghost**
I reworked the register fix from yesterday and it looks fine now. It compiles and compiling is not broken. Simple tests show no anomaly.

### CODE REVIEW

**Comment by krasin** [comment]
Thanks!

fyi: tomorrow (I'm in Pacific timezone, it's 00:19 PST now), I will focus on fixing 'make check', adding first few tests/CodeGen regression tests and upstreaming LabelPrefix (not sure about the latter)

**Comment by ghost** [comment]
Okay. I will refactor the instruction tablegen and will add the last missing basic instructions. (I'm UTC+2)

**Comment by krasin** [comment]
Also, when 'make check' pass, I am going to public a new version of binary distribution (v0.0.3) for Linux x64. The thing is that I don't want to make releases w/o running regression tests anymore.

**Comment by krasin** [comment]
Sounds good, thx

**Comment by ghost** [comment]
Regression tests: Oh yes, please!

**Pull request merged**
