### PR TITLE
Make the EX register more useful and implement rotation

### PR DESCRIPTION
**Pull request by Blei**
See the commits.

I tried to make sure the EX register will not be the target register for instructions that
overwrite EX themselves. IIRC there was a clarification from notch what would happen
in that case, but it just sounds confusing and error prone.

Please tell me if I've overlooked something or if this business can be done in a simpler/
more appropriate manner.

### CODE REVIEW

**Comment by Blei** [comment]
Hmm, this is another one of those patches that _might_ introduce bugs but doesn't either remove bugs nor add much functionality. Maybe keep it for later, when those memset bugs are ironed out?

**Comment by ghost** [comment]
You mean the memset bugs in clang? @a1k0n closed them, for some reason. They _might_ got fixed.

**Comment by ghost** [comment]
Also, I think that EX is a bad general register: We can ONLY address it's content! We can't do stuff like:
[register] or [register + next word]

**Comment by ghost** [comment]
Ah I should read the patch better: You only changed the register addressing mode to use the EX register too. That seems fine.

**Comment by Blei** [comment]
That's why it's not included in the memory operands (DCPU16InstrInfo.td:67 ff). But I'm not sure if this suffices to stop it from being used in memory operands, maybe some other place has to be changed as well...

**Comment by a1k0n** [comment]
I like it.  I'm curious, though: if you were to add the actual EX behavior to the DAG for SHL/SAL/SHR, would it not figure out on its own how to expand ROL/ROR via EX the same way you've done it, as long as GEXR was a target reg class for the 'a' operand of BOR and all the other arithmetic ops?

Ideally I'd also like to add the particular behavior of EX in MUL/MLI/DIV/DVI so that 16x16->32 muls and divs can be implemented without inline assembly or calls to __mulsi3 or whatever.

**Comment by Blei** [comment]
Interesting idea, but I couldn't get it to work. Here's my code if you are interested and want to tinker some more:

```
// Remove the BASIC_BR_NON_COM of SHL in DCPU16InstrInfo.td, add the following

let Defs = [EX], Constraints = "$src = $dst" in {
def SHL16rr : I16rr<0x0,
                    (outs GR16:$dst), (ins GR16:$src, GEXR16:$src2),
                    "SHL\t{$dst, $src2}",
                    [(set GR16:$dst, (shl GR16:$src, GEXR16:$src2)),
                     (set EX, (srl GR16:$src, (sub 16, GEXR16:$src2)))]>;
}
```

It looks like it could work, but it doesn't... Maybe I'm missing something

**Comment by a1k0n** [comment]
I'm trying the same thing with MUL.  Yeah, no dice.  I guess your approach is best; for MUL/MLI we can implement custom lowering for ISD::MULHU/MULHS and SMUL_LOHI and UMUL_LOHI.

**Comment by Blei** [comment]
I have a working SMUL_LOHI here... I hope I haven't duplicated your work :S

**Comment by a1k0n** [comment]
I only managed to add MULHS and MULHU (just by adding a new instruction which does MLI/MUL $dst,$src2; SET $dst, EX) and that worked amazingly well.  This is all I added:

```
let Constraints = "$src = $dst", isCommutable = 1, Defs = [EX] in {
// FIXME: MULH{S,U}16{r,m}{r,m,i} via multiclass
  def MULHS16rr: I16rr<0,
                    (outs GR16:$dst), (ins GR16:$src, GEXR16:$src2),
                    "MLI\t{$dst, $src2}\n\tSET\t{$dst}, EX",
                    [(set GR16:$dst, (mulhs GR16:$src, GEXR16:$src2)),
                     (implicit EX)]>;
  def MULHU16rr: I16rr<0,
                    (outs GR16:$dst), (ins GR16:$src, GEXR16:$src2),
                    "MUL\t{$dst, $src2}\n\tSET\t{$dst}, EX",
                    [(set GR16:$dst, (mulhu GR16:$src, GEXR16:$src2)),
                     (implicit EX)]>;
}
```

(and removed the `setOperationAction`s on MULHS/MULHU as well)

**Comment by a1k0n** [comment]
@krasin, what do you think?  It LGTM, and I want this change.

**Comment by krasin** [comment]
@a1k0n Andy, no need to wait for me. Anyone with commit rights can approve and merge CLs from others (but one cannot approve his own CL, of course)

**Pull request merged**
