### PR TITLE
New README-md

### PR DESCRIPTION
**Pull request by ghost**
I changed our rather old REAMDE.md file. It's a little cleaner now and contains a link to a little SDK I prepared. I replaces the old link to the totally outdated and huge llvm distribution, we created months ago.

### CODE REVIEW

**Comment by krasin** [comment]
@arbaal Nils, is the process of generating the binary distribution documented? Do we have a script for that?

**Comment by ghost** [comment]
Not yet. I will write a bash script to do so sooner or later.

**Comment by Blei** [comment]
LGTM. Thanks for the SDK!

**Comment by ghost** [comment]
I took the liberty to announce this little milestone to the public:
http://0x10cforum.com/forum/m/4932880/viewthread/3089751-status-llvmdcpu16

Since llvm-dcpu16 is in a rather good shape right now (Thank to you @Blei !), it should be very helpfull to other developers.

**Pull request merged**
