### PR TITLE
Use RFI 0 instead of RFI

### LINKED ISSUE #1: Create lib/Target/DCPU16 directory
Make it a clone of MSP430.

### PR DESCRIPTION
**Pull request by L3nn0x**
This should fix #1

### CODE REVIEW

**Comment by krasin** [comment]
Hi L3nn0x,

I think that llvm-dcpu16 is currently in museum mode: it only has a historical value, and there're no plans to change it, because 0x10c (the game) didn't happen.

Are you aware of any practical use for this code?

**Comment by L3nn0x** [comment]
Hi krasin,

Actually this PR was a mistake I did when I created it, I never thought someone would answer here ^^

There is actually a new game in development that will use DASM and variants of the DCPU : techcompliant.

Here is the reddit about it : https://www.reddit.com/r/techcompliant/
It is quite alive at the moment, with quite a lot that was added to the DCPU (everything DCPU related can be found here : https://github.com/techcompliant/TC-Specs)

My team and I are trying to use llvm-dcpu16 to re-write our OS (FrOSt) in C for this new game.
To be honest, it's a bit clunky to use, especially when trying to use inline asm.

Anyway, thanks for taking the time to answer!

**Comment by krasin** [comment]
Oh, sounds interesting. I'll take my time to skim through /r/techcompliant

Note: this LLVM backend is considered as a partial failure on my behalf, as 16-bit char is a tough call for C, and there're many known cases, when it's not working as intended. Still, if you find the code working for you, I am happy.

Since this PR was created by an accident, I will close it. Thanks again for giving a hint about techcompliant!

**Comment by L3nn0x** [comment]
No problem!

Alright I'll keep it in mind and I'll try to improve it. We'll se how it goes ;)

**Pull request closed without merging**
