### PR TITLE
Merge with LLVM upstream

### PR DESCRIPTION
**Pull request by krasin**

### CODE REVIEW

**Comment by krasin** [comment]
@a1k0n 
The meaningful change is the last 2 commits. Please, take a closer look

**Comment by a1k0n** [comment]
LGTM

**Comment by a1k0n** [comment]
It doesn't fix the particular issue I'm having (internal compiler errors) but my previous stuff all still works.  I'll do some digging and post some issues.

**Comment by krasin** [comment]
What're the internal compiler errors do you have? Can you please file them as bugs? Are they dcpu16- or llvm- related?

**Comment by a1k0n** [comment]
There are two, and they appear to be related to both, kinda.  I am trying to narrow them down a little bit.  It seems that our ISelDAGToDAG is creating a cycle in the DAG, somehow, somewhere, on a very simple function within a relatively complicated program.

I will file bugs.

**Pull request merged**
