### PR TITLE
DCPU16: Renamed all registers and deleted FP references

### PR DESCRIPTION
**Pull request by ghost**
This is a rather big change. It renames all registers adds the
SP and O registers AND removes all references to the frame
point register, which we never used. I think that branch prediction
was and is right now broken. We really need to find a way to
validate our code soon. When this change has been approved,
I will refactor the instruction tablegen with multiclasses, since
right now, it has much duplicated code, which would be hard
to maintain otherwise.

Commit message:

Our targets now contains only the registers, the DCPU16
specification contains. I also removed all FP refrences,
since we don't use a frame pointer (We never did).

Signed-off-by: Nils Hasenbanck nils@hasenbanck.de

### CODE REVIEW

**Comment by krasin** [comment]
Looking into this. Filed #69, because it really becomes an issue.

At the first glance, the change is fine. I would probably skip testing on my side, because my desktop has become out of order few hours ago (SSD died) and my laptop is pretty slow.

**Comment by krasin** [comment]
I have just finished merging with LLVM upstream and this change cannot be automatically merged anymore. Could you please resolve conflicts?

**Comment by krasin** [comment]
Hm... looks like the conflict is not related to merge with LLVM upstream.

**Comment by krasin** [comment]
Anyway, the change looks good to me. Feel free to merge and pull this CL yourself

**Comment by ghost** [comment]
I'm resolving the issue. Sometimes I really hate DVCS. ;)

**Pull request merged**
