### PR TITLE
Expand jumptables

### PR DESCRIPTION
**Pull request by Blei**
Jump tables will be expanded to a series of BR_CCs. This produces slightly awkward code, but is probably good enough for now. Maybe I'll see how to do it correctly later on.

### CODE REVIEW

**Comment by a1k0n** [comment]
Meh, it doesn't seem to fix my particular issue.  Please add a switch/case test too.

It does work in a trivial example, though.  Hmm.

**Comment by a1k0n** [comment]
Small example which fails:

```
int switchcase(int c)
{
  int x = 0;
  switch(c&3) {
    case 0:
      x ^= c;
      break;
    case 1:
      x -= c>>8;
      break;
    case 2:
      x += c<<8;
      break;
    case 3:
      x ^= c*2;
      break;
  }
  return x;
}
```

**Comment by Blei** [comment]
Hmm, apparently my tiny example got optimized to a series of ifs even before codegen :P I'm on it.

**Comment by Blei** [comment]
New version has been `push -f`ed.

**Comment by a1k0n** [comment]
Awesome stuff.  LGTM.  Thank you!

**Pull request merged**
