### PR TITLE
DCPU16: Fixes issue 81 zero extend fix

### PR DESCRIPTION
**Pull request by ghost**
I fixed issue 81 and changed some handling of the i8 type. I promoted nearly all i8 operations and did some changes to change the target to a nearly pure 16-bit word based CPU.

### CODE REVIEW

**Comment by ghost** [comment]
I begin to lightly hate myself (or github) ...

**Comment by krasin** [comment]
@arbaal what's wrong with you (or github)?

thx for fixing this!

**Comment by ghost** [comment]
I just get confused with my branches/rebases/merges .... I already did the changes three times ...

**Comment by krasin** [comment]
btw, this pull request is not merged and closed. Should I reopen and merge it?

**Comment by ghost** [comment]
No, I will reopen another, which can be automatically merged.

**Pull request closed without merging**
