### PR TITLE
Optimize BR_CC

### PR DESCRIPTION
**Pull request by Blei**
Lower BR_CC to more efficient code. Also general cleanup, as the complicated CMP instructions aren't needed anymore.

I'm somewhat confident that the code mostly does what it should, but I would be very grateful if someone more knowledgeable about LLVM could look at it before merging.

This patch might interfere with the work on the SETCC instruction, but it should be quite easy to integrate the two patches I think.

### CODE REVIEW

**Comment by krasin** [comment]
Thank you for the work.

First pass: general comments.
1. Make sure that LLVM regression tests pass (may be, you have already done this):
   
   ```
     make check -j4
   ```
   
   Since you have only changed Target/DCPU16 code, it may be faster to run just DCPU16 tests:
   
   ```
   bin/llvm-lit -v ../test/CodeGen/DCPU16/
   ```
2. Please, check if any of currently disabled tests under test/CodeGen/DCPU16 may be enabled
3. If the set in p2 is empty, it would be nice to add a couple of tests. This is OPTIONAL. I appreciate your work and ready to add tests myself. I just assume that you might generate better tests than me, because you better understand the logic of BR_CC.

**Comment by Blei** [comment]
Thanks for your comments. I already found some bugs by looking through the tests!

I just noticed that signed comparison is probably very broken. Should I try to expand it to correct code or should I wait for Notch to release the updated spec (that hopefully contains signed comparison)?

**Comment by krasin** [comment]
Yes, don't bother with signed ints for now, it's a different story, #107. Just make sure that signed types work as intened on small non-negative numbers, so 2 < 3, and 5 > 1.

**Comment by krasin** [comment]
It looks like I don't get an email if another commit is added.

@Blei is it ready to be merged or you want to add anything to this pull request?

**Comment by ghost** [comment]
I will pull this patch later the day. Probably @asl will pay us a visit and has some comments about it. I will have a closer look myself later the day.

**Comment by krasin** [comment]
@arbaal currently, the patch is not ready for the merge, because it will make some confusion later: when pushing to master, it's always better to have small commits and a correct state after every commit. Otherwise, it will confuse `git bisect`, if running later.

I was going to wait a reply from @Blei and after that review it and merge manually. If you think that you have time for the proper commit queue, feel free to go. But it's kind of `dirty work`, I am fine to do it myself.

**Comment by ghost** [comment]
Okay, I never stop people who want to do the hardwork. ;)

**Comment by krasin** [comment]
:)

**Comment by ghost** [comment]
Okay, looked over it.
+1 from me. The code is much simpler (for now) and will be a good foundation for further improvements.

**Comment by Blei** [comment]
Okay, I added some tests and I think it should mostly work now. But I still think it would be a good idea if @asl or someone else would have a look.

**Comment by krasin** [comment]
I have started to merge this CL. Will update this thread soon.

**Comment by krasin** [comment]
The manual merge is complete and I have created another pull request, see #109. Closing this to move the discussion to the most recent version.

I hope that everything is fine, but if somebody would take the last look before it's merged to dcpu16 branch, I would be thankful.

**Pull request closed without merging**
