### PR TITLE
The function signature of TargetRegisterInfo::getPointerRegClass changed

### PR DESCRIPTION
**Pull request by Blei**

### CODE REVIEW

**Comment by krasin** [comment]
Thanks for spotting this!

While merging, I have also resolved one or two similar issues (which broke tests). Is it possible to require a method to override a virtual method in the base class, so that we'll get a compiler error next time a signature is changed?

**Comment by krasin** [comment]
LGTM

btw, what was the test case that helped you to spot this issue?

**Comment by Blei** [comment]
Apparently there is no such thing (I'm actually surprised c11 didn't fix this): http://stackoverflow.com/questions/497630/safely-override-c-virtual-functions

re testcase: it was clang's warnings when building the project :P

**Comment by krasin** [comment]
At least, I now understand why C# has `override` keyword.

Thanks again!

**Comment by Blei** [comment]
Scratch that, apparently [C++11 did fix that](http://en.wikipedia.org/wiki/C%2B%2B11#Explicit_overrides_and_final). But I don't know how well it's supported by compilers yet (works in current clang at least, but msvc..?)

**Comment by krasin** [comment]
It might be a good question for #llvm irc, what's their position about using C++11 for LLVM/Clang code.

**Comment by Blei** [comment]
Heh, i had the same idea:

```
Blei | what's the policy of llvm for using new language features?
chandlerc | Blei: we're trying to support N+1 MSVC releases
chandlerc | that tends to be the slowest-moving compiler we maintain compatibility with
[...]
Nikola | ok, so N+1 means 2008 and 2010
```

And `override` is planned to arrive in [VC11](http://blogs.msdn.com/b/vcblog/archive/2011/09/12/10209291.aspx)

**Comment by krasin** [comment]
Interesting, thanks!

**Pull request merged**
