### PR TITLE
DCPU16: Added regression test for issue #81

### PR DESCRIPTION
**Pull request by ghost**
This regression test will fail for now, but puts the pressure up to fix it!

### CODE REVIEW

**Comment by krasin** [comment]
Let me check if LLVM test suite can have disabled tests. If 'make check' fails to run, it's unlikely to be run by people.

**Comment by ghost** [comment]
If it don't support disabled tests, let's wait with the pull after we found a solution.

**Comment by krasin** [comment]
Sure, it has:

```
Testing Time: 57.52s
  Expected Passes    : 5828
  Expected Failures  : 50
  Unsupported Tests  : 13
```

Please, add this test to the expected failures. Also, I would prefer not having special symbols like '#' in the file names.

Feel free to name the test like YYYY-MM-DD-issue-XX-i8-zeroext.ll or something (you might want to look around for the test names in other targets)

**Comment by krasin** [comment]
Sorry, I have not spotted that you have already put "; RUN: llc < %s -march=dcpu16 | not grep {UNREACHABLE|ERROR}"

I was under assumption that it will count as unexpected failure, but this counts to "pass". It's acceptable. Merging.

**Comment by krasin** [comment]
Argh! :)
I was wrong again. Fixing...

**Comment by ghost** [comment]
You can fix the filename when you're at it. ;)

**Comment by krasin** [comment]
Fixed by de94191a64b2bd50d103c87dafaedfe122ead1f2

**Comment by krasin** [comment]
Yes, I have fixed the filename in ead5ce80df7b292127043d60a18a30b3cd3de485
Thanks for adding the test.

**Pull request merged**
