### PR TITLE
DCPU16: Issue 81 zero extend fix

### PR DESCRIPTION
**Pull request by ghost**
This will fix issue #81 and also change the default behavior for the target to handle i8 types.

### CODE REVIEW

**Comment by ghost** [comment]
Don't merge yet.

**Comment by ghost** [comment]
Ah no okay, I just used the wrong compiler and thought I had forgotten something. But it's okay.

**Comment by ghost** [comment]
Updated the pull request to include your old changes.

**Comment by krasin** [comment]
LGTM

**Comment by krasin** [comment]
btw, have you mentioned https://github.com/DylanLukes/DCPU16-LLVM-Target ?
they claim to write DCPU16 target from the scratch, not rewriting MSP430 (although, I don't see a benefit here, to be honest)

**Comment by ghost** [comment]
I did try to write one for myself from scratch but failed. They seem to use parts of MSP430 too, so I don't see the benefit at all ... we should probably just join forces.

**Comment by krasin** [comment]
I would appreciate that, but I'm not sure if the author of that repo wants this.

**Comment by ghost** [comment]
I think there is just one way to know: We have to ask. And with "We" I mean "You" because it's your name that's in front of the repo. ;)

**Comment by krasin** [comment]
btw, when known crashes are fixed, it would be a good time for the new binary release. Also, since DCPU emulators have become more stable and support keyboard/terminal, it would make sense to address #31

**Comment by ghost** [comment]
Let's worry about that when the code is ready to go. ;)

**Comment by krasin** [comment]
I'm fine to ask.

Regarding to the repo for the project, I would like to create a github "organization" and move the repo there. I will try to understand how to make this later today.

**Comment by ghost** [comment]
Okay. We should then just find a way to "announce" it, so people will find it.

**Comment by krasin** [comment]
That's the trick. I _hope_ that github allows to move the repo to the organization with all the watchers and forks. Otherwise, it absolutely does not make sense.

**Comment by krasin** [comment]
OK, I have created [llvm-dcpu16](https://github.com/llvm-dcpu16) organization, granted you a push access and moved clang-dcpu16 there (since it has fewer watchers and it's safer to experiment) and renamed clang-dcpu16 to [clang](https://github.com/llvm-dcpu16/clang), because it will make it easier to git clone the repo and will reduce the change to make a mistake.

No issues so far.

Let's try it for one or two days and move the main llvm repo, if everything looks fine.

**Comment by ghost** [comment]
Okay. Did the issues migrated too?

**Comment by krasin** [comment]
Actually, that repo didn't have any issues

**Comment by krasin** [comment]
But github promises that it should

**Pull request merged**
